### ISSUE TITLE
Replacing a player does not work as intended

### ISSUE THREAD

**Issue by Zrp200** [smogon/pokemon-showdown-client#1090]
This can be fixed in [client-battle.js](https://github.com/Zarel/Pokemon-Showdown-Client/blob/master/js/client-battle.js).

Essentially, when one decides to replace a player, `/addplayer [username]` is called, but the server is expecting `/addplayer [username], p1` or `/addplayer [username], p2`, thus causing the action to fail on the server. After this failure, the player who called this is no longer in the battle as a player, but their slot is now empty.

**Comment by Zarel** [comment]
Do you plan on providing the fix?

**Comment by Zrp200** [comment]
I don't know how exactly to fix it, else I would have submitted this as a
pull request. I'm sorry, I should have clarified.

**Comment by Zarel** [comment]
Okay, good to know. I can work on this when I have time.

**Comment by PartMan7** [comment]
Oh, this is active. 

[This](https://github.com/smogon/pokemon-showdown/commit/ba6008e488a6a5e33ec3c6cf5b48779d3a361e5c) should've fixed it; can someone mark this as resolved?
