### ISSUE TITLE
Issues with desktop client

### ISSUE THREAD

**Issue by scheibo** [smogon/pokemon-showdown-client#1278]
I got a ticket from a Windows 10 user who experienced some issues with the desktop client (ie. standalone, not the browser). A summary:

> during a battle their client froze (screen turned white, _'it basically has the *Username* vs. *Opponent* on the top and the rest below it just a white screen'_, was not responding). apparently this is a typical symptom whenever their internet is unplugged but their internet was fine this time, and they killed and restarted the client fairly quickly, (estimate _'~30-45s'_) and when the arrived back they saw the active battle _'seems to have disappeared (normally there is a button to get back into active battles, it appeared for a second and then disappeared quickly) '_.

My best theory is that the desktop client (perhaps erroneously) figured they were disconnected, and by the time they noticed the client not responding and restarted the 60s disconnect timeout had passed, which was ruled as potentially plausible by the user (my other theory was maybe their opponent didnt feel like waiting and just left the battle, but the user lost ELO so presumably that wasn't the case). I don't know enough to be able to say that was actually what happened (does the battle get removed from active battles in that scenario? I would have thought that unless the 15 minute inactivity period had passed and expired the battle it would still be there?)

Anyway, several issues/questions here:

- the desktop client should not 'white out'/become inactive on the network disconnecting (sounds more like a crash?)
- the desktop client should not consider the network inactive when it isn't
- what is the approach for debugging node webkit issues? Do we get any logs/[crash dumps](https://github.com/nwjs/nw.js/wiki/Crash-dump) etc? Asking the user to open a console and scan for errors doesn't appear to be an option.

**Comment by Zarel** [comment]
A new desktop client needs to be deployed ASAP but I've been putting it off... Signing is annoyingly hard and new deployments all require signing these days, if you don't want to teach your users how to turn off checking for signed executables.

**Comment by scheibo** [comment]
> A new desktop client needs to be deployed ASAP

Is the 'white out' a KI already that the new client would fix? And does the new desktop client have better support for debugging issues?

**Comment by Zarel** [comment]
Is it reliably reproducible? If so, you can test yourself by grabbing the latest version of Node-webkit and following the desktop client build readme: https://github.com/Zarel/Pokemon-Showdown-Client/tree/master/desktop

**Comment by Zarel** [comment]
The old desktop client is pretty easy to debug: Just turn on the toolbar in `package.json`, Chrome's debugging tools are the gear icon on the toolbar.

**Comment by Zarel** [comment]
New desktop client was deployed a monthish ago.

**Comment by Zarel** [comment]
Sadly, opening devtools on it is a lot harder, but can be done with `/debug nw`.
