### ISSUE TITLE
Import from URL

### ISSUE THREAD

**Issue by scheibo** [smogon/pokemon-showdown-client#1349]
The teambuilder should allow importing a team from a URL (`/raw/` for pokepast.es, pastebin, hastebin, gist). If/when Smogon implements a team dex, we should support those URLs as well.

The main use case is to cut out the select all + copy steps from team importing which can be especially obnoxious on mobile. 

CORS/XSS implications are important to consider for this feature.

**Comment by scheibo** [comment]
@Slayer95  suggested allowing importing a set from Smogon via URL which also an option, though there'd need to be some sort of prompt to determine which set is desired.

```
Choose Monotype Klefki's set
> * Dual Screens (Fairy)
* Dual Screens (Steel) 
```

I think this is worth adding, but potentially as a followup because its more involved and less impactful (one set at a time instead of entire teams)

**Comment by Zarel** [comment]
Do the named services support CORS, or do we need to proxy them?

**Comment by scheibo** [comment]
Proxying will probably be the way to go. We can presumably create a PR to have pokepast.es support CORS (cc/ @felixphew), but [Pastebin appears likes its going to need a proxy unless the paste was created by a "Pro" user](https://twitter.com/pastebin/status/916213585960947712). Hastebin/Gist ???

**Comment by felixphew** [comment]
I've wanted to do this with PokePaste anyway - just let me know what origins I need to allow. Just `https://play.pokemonshowdown.com`, or are there alternate / testing / etc. domains I should turn on too?

Also, I imagine that you'd want to grab the [/json](https://pokepast.es/a50b2e12adbcda5f/json) or [/raw](https://pokepast.es/a50b2e12adbcda5f/raw) URLs from PokePaste instead of scraping.

**Comment by Slayer95** [comment]
@felixphew That would be ``play.pokemonshowdown.com`` and ``*.psim.us`` (side servers, tournaments, testing, etc.). Pretty please !

**Comment by felixphew** [comment]
I've thought about it, and given (a) URLs are supposed to be unguessable, and (b) those two sub-paths are designed to be scraped, I'm just going to set `ACAO: *`. Makes it easier for others trying to build these integrations in the future.

**Comment by Zarel** [comment]
Yeah, PS sets all our JSON endpoints to ACAO `*` for exactly this reason.

**Comment by Zarel** [comment]
Unrelatedly: It looks like Gist also allows CORS. I couldn't test Hastebin (it looks like it's down right now).

**Comment by scheibo** [comment]
I vote we support all the CORS friendly sites first and if the feature is popular we can consider supporting the others through proxying as a followup.

**Comment by scheibo** [comment]
OK, wrote some logic for being able to take a gist/hastebin/pokepaste URL that a user may throw at us and parse it into a 'raw' URL: https://gist.github.com/03cd109318081a7b727d4b0ec38245b9

Some questions:

1) Should we use the same import box and just have it also accept URLs (or multiple lines worth of URLs?) or do we create an 'import from URL' box for an individual URL? (leaning towards the former?)
2) Does this logic belong in `Storage.importTeam` - its currently a pure and synchronous function, having it perform (potentially multiple) HTTP requests changes things
3) `Storage` seems to already do some jiggery-pokery to finagle cross origin requests (possibly only for a specific request? and with workarounds for the desktop climb). Can/should that be generalized and used for this?

**Comment by scheibo** [comment]
@Zarel ^

**Comment by Zarel** [comment]
> Should we use the same import box and just have it also accept URLs (or multiple lines worth of URLs?) or do we create an 'import from URL' box for an individual URL? (leaning towards the former?)

whynotboth.jpg

Maybe the button should just give a popup that says "You can paste the URL right into the import box".

> Does this logic belong in Storage.importTeam - its currently a pure and synchronous function, having it perform (potentially multiple) HTTP requests changes things

I would put it higher-level.

> Storage seems to already do some jiggery-pokery to finagle cross origin requests (possibly only for a specific request? and with workarounds for the desktop climb). Can/should that be generalized and used for this?

Possibly. I'm not sure the weird cross origin requests are even necessary anymore; they're I think a workaround for before CORS support was common (for ~IE9). I think I'm fine with only supporting the official server for IE9.

**Comment by scheibo** [comment]
<img width="827" alt="Screen Shot 2019-10-06 at 11 57 24" src="https://user-images.githubusercontent.com/117249/66274156-87724d00-e830-11e9-96c8-68eb68c9a854.png">

From the new Smogon Discord RMT channel: This makes me feel this integration should maybe even go both ways - in addition to just import from pokepaste URL, I think it would also be nice to make a button to just immediately get a link to the export of the team you just created to remove the steps of having export + copy the text to pokepaste to upload + copy the URL.

@felixphew - I haven't had a chance to make any further progress on importing from a URL than the code in the gist linked above. Do you have any interest in working on this integration? I'd be more than happy to help/provide guidance if you need it, but I haven't had the time to work on this feature directly.

**Comment by BlueWinds** [comment]
I believe this ticket could be closed, unless you want to leave it open for additional features? I'd be happy to open another PR if there's more you'd like to see happen with this feature.

**Comment by Zarel** [comment]
I'm not aware of additional features being needed, but feel free to suggest them if you do.
