### ISSUE TITLE
Add feature to challenge user using name at top of pm window

### ISSUE THREAD

**Issue by jordanhui19** [smogon/pokemon-showdown-client#1384]
I was battling a friend during a voice call, and noticed there was no way to send them another them without searching their name again, since we weren't using the in-game chat.

I want to add a feature where clicking their name in the top of the pm window brings up the challenge menu the same way clicking their name in a pm message does.

Seems like this pretty simple to implement so I should be able to do it myself.

**Comment by Zarel** [comment]
At the end of the battle, there's a "Rematch" button.

**Comment by Zarel** [comment]
Anyway, the new Preact client fixes this with user lists in PMs. If someone else wants to fix this in the old client, feel free.

**Comment by jordanhui19** [comment]
I after each match we made new teams, so we couldn't just rematch. I thought it was inconvenient to have to search for someone you already have a pm window open with, and I figured it'd make sense to be able to rematch from there.

**Comment by Zarel** [comment]
The Rematch button lets you choose a new team and format.

**Comment by jordanhui19** [comment]
Can you access teambuilder from rematch?

**Comment by Zarel** [comment]
Yes... The Rematch button literally does the same thing as the Challenge button.

**Comment by jordanhui19** [comment]
Huh okay, didn't realize the challenge window stays open if you go into teambuilder.
Still, I think its weird that clicking a username anywhere but the header of the pm lets you challenge them.

**Comment by Zarel** [comment]
The team selector in the challenge window (and everywhere) also contains a Teambuilder link.

I do agree there should be some way to challenge from a PM window, though.

**Comment by DaWoblefet** [comment]
This was done in https://github.com/smogon/pokemon-showdown-client/pull/1385
