### ISSUE TITLE
Resume button visible behind play button

### ISSUE THREAD

**Issue by JacenBoy** [smogon/pokemon-showdown-client#1387]
On downloaded replays, when the page first loads, the "Resume" button is visible behind the "Play" button.

![replay](https://user-images.githubusercontent.com/11392691/67805650-bcf10b80-fa67-11e9-8a52-f9dae9efdd1f.png)

**Comment by jordanhui19** [comment]
I can work on this one.
@Zarel how would I test replay-embed.js with a downloaded replay?
Would I have to make a new replay with testclient?

**Comment by Zarel** [comment]
You can just edit the downloaded replay source to point to your own copy of `replay-embed.js`

**Comment by Zarel** [comment]
Fixed by 6b9ff7a3c4256e0
