### ISSUE TITLE
Max moves don't show the correct Base Power in hover tooltip

### ISSUE THREAD

**Issue by TZubiri** [smogon/pokemon-showdown-client#1399]
The base power of Max moves caps is correctly calculated server side, but is not shown correctly when hovering over the moves.

Minimum verifiable example:
Snorlax has facade, giga impact and self destruct. Turn 1 snorlax uses facade, turn 2 uses dynamax and giga impact, turn 3 uses self destruct.
https://replay.pokemonshowdown.com/gen8ou-1013032453

Here is a resource that shows the correct base powers of Max strike.
https://www.serebii.net/attackdex-swsh/maxstrike.shtml

The tooltip should be showing 150BP for the giga impact and self destruct slots when dynamaxing.

Additionally, the tooltip should continue to show Max Strike during the 2nd and 3rd turns.

Original user report:
https://www.smogon.com/forums/threads/bug-reports-v3-read-original-post-before-posting.3634749/post-8287990

**Comment by Zarel** [comment]
Fixed in bb984e421307d7f

**Comment by TZubiri** [comment]
🔥
