### ISSUE TITLE
Ditto should not be able to dynamax if the pokemon it copied cannot dynamax (Eternatus).

### ISSUE THREAD

**Issue by TZubiri** [smogon/pokemon-showdown-client#1400]
Currently, the ditto player is presented with the ability to dynamax, but error messages are shown if the user tries to do so.

Example game:
https://replay.pokemonshowdown.com/gen8anythinggoes-1013044089

Original user report:
https://www.smogon.com/forums/threads/bug-reports-v3-read-original-post-before-posting.3634749/post-8288249

**Comment by Zarel** [comment]
This is most likely already fixed, and isn't a client bug, anyway.
