### ISSUE TITLE
'Favorite user' system to quickly access frequent opponents

### ISSUE THREAD

**Issue by jordanhui19** [smogon/pokemon-showdown-client#1420]
Since there isn't a friend system in place yet, I think it would be useful to be able to save users that you frequently play against, then have a quick-access menu that shows the names of the players you added.
It'd save people the trouble of having to remember and search usernames every time.

**Comment by Zarel** [comment]
It's an interesting idea, but this is also just called a friends list by many people.

I'm sometimes fine with stopgaps but I don't think I like this one; it would be hard to transition over.

**Comment by monsanto** [comment]
We added a friends system, please reopen if there is something specific you'd like to see from it.
