### ISSUE TITLE
'Unrevealed Illusion User' as seventh pokemon even though the illusion user was revealed.

### ISSUE THREAD

**Issue by Gamebuster19901** [smogon/pokemon-showdown-client#1427]
The following replay is displaying an extra pokemon as 'Unrevealed illusion user'. The illusion user was cottonee, and was revealed on turn 3. 'Unrevealed illusion user' appears on turn 29. This issue is related to #314

<s>Additionally, Hitmonchan appears duplicated on turn 12 but with different stats.</s>

https://replay.pokemonshowdown.com/gen8hackmonscup-1031863909

![image](https://user-images.githubusercontent.com/7155747/71169536-2ea73380-2227-11ea-983d-2805a75a521d.png)

**Comment by Zarel** [comment]
Ugh, Hackmons Cup.

**Comment by Zarel** [comment]
Hitmonchan being duplicated on turn 12 is not a bug. Unless Hackmons Cup can never generate two Hitmonchans, in which case it's a server bug (the server should send Species Clause), not a client bug.
