### ISSUE TITLE
Setting a Pokemon's level in generation 1 and hitting enter disconnects the client

### ISSUE THREAD

**Issue by davidstone** [smogon/pokemon-showdown-client#1526]
Steps to reproduce:

* Create a generation 1 team
* Add a Pokemon
* Select its Species
* Click on "Level"
* Enter a valid number into the level field
* Hit enter

This occurs for me on Firefox on Linux

**Comment by PartMan7** [comment]
Can confirm, though the issue isn't limited to Gen1.
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8466937 A bit more on it.
