### ISSUE TITLE
It is possible to reach Zarel in-game

### ISSUE THREAD

**Issue by tildearrow** [smogon/pokemon-showdown-client#1599]
In Super Staff Bros Brawl mode, it is possible to reach Zarel without any warning, unlike through the "Find a user" option, or a chat room.

Normally it would display a warning:

<img src="https://user-images.githubusercontent.com/13842506/90356457-2239db80-e03f-11ea-9d20-e6e5783130a3.png" alt="zarel1" width=302.5/>
<img src="https://user-images.githubusercontent.com/13842506/90356462-236b0880-e03f-11ea-8a67-5a07fab02984.png" alt="zarel2" width=529.5/>

However, when switching to the Zarel Pokémon in SSBB, it works, by clicking its name:

<img src="https://user-images.githubusercontent.com/13842506/90356463-236b0880-e03f-11ea-85a7-dea35f51f493.png" alt="zarel3" width=530/>
<img src="https://user-images.githubusercontent.com/13842506/90356465-24039f00-e03f-11ea-86cf-0ef9e09f8367.png"  alt="zarel4" width=320/>

I am not sure if this is a bug or not, but I know it should not be possible to reach Zarel in-game...

**Comment by Zarel** [comment]
This is not a bug. There have always been multiple ways to reach me. I only block the "Find a user" dialog to cut down on spam.

**Comment by Zarel** [comment]
The usual way I recommend is `/user Zarel`, by the way.
