### ISSUE TITLE
[REQUEST] Don't send passwords as plaintext

### ISSUE THREAD

**Issue by nxg9997** [smogon/pokemon-showdown-client#1610]
I've been poking around with the PS api to learn a little bit about how it works, and I noticed that when logging in or registering an account **passwords are sent as plaintext in a query URL to the login server**. This should be changed immediately since it is a huge security risk for people on public networks (especially if a user uses the same password for other websites/accounts!), and nobody seems to know about it. I believe the request is being formed inside /js/client.js, but I am not familiar enough with how PS works to submit a fix, and there is nowhere to view the source for the login server to submit a change to that either

**Comment by AnnikaCodes** [comment]
> there is nowhere to view the source for the login server to submit a change to that either

The loginserver is open source. It's contained in the `.php` files in the root of this repository as well as in the `lib/` folder.

**Comment by Zarel** [comment]
Passwords aren't sent in plaintext, they're encrypted by TLS. Do you not understand how HTTPS password authentication works? I'm not sure I'm equipped to teach this.

**Comment by Zarel** [comment]
I really don't want to deal with crypto cranks. We use the same authentication flow used by major companies like Google and Facebook and basically every other website: send password over HTTPS, receive session cookie. The server-side password verification uses bcrypt, which is also standard (for this one I can't speak for big companies who keep their servers closed-source, but the standard in open source is bcrypt or pbkdf2).

If you have some weird new idea you think is more secure, well, chances are you're wrong. But, even if you're right, the right place to experiment with new security ideas isn't a pokemon simulator. Get hired by Google's security team or something; none of us here are qualified to judge whether or not your weird new idea has major security holes.
