### ISSUE TITLE
Show Password Button Conflicts with Password Text Field

### ISSUE THREAD

**Issue by mashirochan** [smogon/pokemon-showdown-client#1717]
Sadly, the new show password button that was just added has a couple issues - it appears to be overlapping the password text field, so it can only be clicked on the very far right of the button. Also, I've noticed that pressing enter now interacts with the show password button, instead of the log in button. This seems to be an inferior interaction, because I'd imagine most users would rather login quickly than show their password quickly.

https://i.imgur.com/eNnuZco.gif

**Comment by urkerab** [comment]
Looks like this is because the button doesn't have the right `type` attribute, so it's defaulting to a submit button. I checked in Developer Tools and adding `type="button"` seems to fix the problem.

**Comment by Zarel** [comment]
Out of curiosity, what browser is this? Firefox?

**Comment by mashirochan** [comment]
Yeah, Firefox 85.0 (64-bit) on Windows 10

**Comment by Zarel** [comment]
Fixed.
