### ISSUE TITLE
1250 Replays limit in a search

### ISSUE THREAD

**Issue by grenvol** [smogon/pokemon-showdown-client#1726]
By digging, I noticed a limit to only the last 1250 replays (25 pages) when going backwards in a search, it is pretty limitating when trying to make metagames analysis based on it since over the 1250 there are around 3% that belong to the same person using the same team. I'm not sure why there is such limit, loading time is still fast (200ms) when trying to get the 25th page. 
Having access to up to 100 page would be a good improvement to start with.

It's written in the code there: https://github.com/Zarel/Pokemon-Showdown-Client/blob/master/replays/search.php#L116

**Comment by Zarel** [comment]
The limit is there for database performance reasons. I don't feel comfortable raising it at this time. 200ms isn't very fast from a hostile attacker's perspective.

**Comment by grenvol** [comment]
@Zarel Fair, but is there any way to see older replays?

**Comment by xfix** [comment]
Is there a reason why we use [`OFFSET` pagination instead of seek pagination](https://use-the-index-luke.com/sql/partial-results/fetch-next-page)?

**Comment by Zarel** [comment]
> Fair, but is there any way to see older replays?

@grenvol yes, you just can't search them.

> Is there a reason why we use [`OFFSET` pagination instead of keyset pagination](https://use-the-index-luke.com/no-offset)?

That might be a good thing to change, yes.
