### ISSUE TITLE
SockJS SecurityError

### ISSUE THREAD

**Issue by wrodd** [smogon/pokemon-showdown-client#1790]
All content fails to load (hangs indefinitely) whenever I try to reach https://play.pokemonshowdown.com/, and I see a SecurityError in the JS console

<img width="1440" alt="Screen Shot 2021-05-11 at 4 19 53 PM" src="https://user-images.githubusercontent.com/31630861/117896258-01708080-b275-11eb-9a39-5ff1dedcd755.png">

Has anyone else run into this?

**Comment by mia-pi-git** [comment]
This is known. The main server is down for everyone - just be patient, we're working on it.

**Comment by wrodd** [comment]
Sure thing, thanks for the update! Just curious, is there somewhere else I should have gone to check this before posting the issue?
