### ISSUE TITLE
Missing GMax Sprites

### ISSUE THREAD

**Issue by enlighten1self** [smogon/pokemon-showdown-client#1836]
Is this the right place to report this?

The sprite libray is missing some Gmax forms in the /ani folder. The one i know are blastoise, cinderace, and rillaboom. 

thank you! i love this website, great work!!

**Comment by Zarel** [comment]
This is definitely a problem, but not the sort of thing we have the ability to fix in-house. Usually we have users give us the sprites. Do you have sprites you can give us?

**Comment by enlighten1self** [comment]
I will work on it. I am currently getting together a JSON file with short and long descriptions on pokemon from pokemondb. is this something you would be interested in implementing?

**Comment by Zarel** [comment]
Do you mean Dex entries? We don't really use those.

**Comment by enlighten1self** [comment]
Yes, no problem. Feel free to close this, I will send sprites if I can manage to make them look good. Thank you!
