### ISSUE TITLE
Avatar 'Red' selection problem

### ISSUE THREAD

**Issue by KJeff01** [smogon/pokemon-showdown-client#1837]
One of the avatars for Red can't be selected: avatar 162 (arm down, cap covering eyes). Attempting to click it appears to select avatar 163 instead (Red looking up and touching his cap).

`BattleAvatarNumbers` is using the same name, 'Red', for both 162 and 163. Perhaps it's possible the avatar gets set via the avatar name and then the client chooses the last one. Avatars 167 and 168 would suffer from the same issue I suppose as they share the exact 'Unknown' name too.

**Comment by Zarel** [comment]
These seem to have been removed for being redundant. Sadly, we don't have a record of why this was done, but they should no longer appear in the avatar selector.
