### ISSUE TITLE
In-battle damage calculator

### ISSUE THREAD

**Issue by leungbk** [smogon/pokemon-showdown-client#1870]
It would be nice if the presently-empty lower-left quadrant(-ish) of the display (on desktop) had a damage calculator.

It feels a little bit cumbersome to use the existing calc-pokemonshowdown site to (if playing a match for blood) open one or more tabs for each of your Pokemon, fill them yourself with your Pokemon's EVs/moves/etc., and either change tabs or change the opposing Pokemon to a new target if I want to determine how damage my Pokemon does to some other opposing Pokemon. Even if you're not playing for blood, since most players don't know the damage calcs for every move against every possible matchup for each of their Pokemon, a convenient display could save them some time by allowing them to learn the damage ranges for a particular metagame as they come up in a match as opposed to inputting them manually after the game (if ever).

The LHS could have the player's six Pokemon, populated with their EVs/moves/etc., while the RHS could have an arbitrary number of candidate slots for opposing Pokemon which the player can fill in based on, for example, what they think the EVs might be or what moves they may have. If I want the calculations for my Pokemon A vs. some possible spread for my opponent's Pokemon X, I would click the buttons corresponding to A and the candidate X. On desktop, I can see this looking somewhat similar to the existing calc-pokemonshowdown display, though I'm not sure how good it would look on mobile.

**Comment by mia-pi-git** [comment]
While we do have a plan to add a command for doing battle calcs (which will likely serve your purpose), this is not a place for suggestions. [this](https://www.smogon.com/forums/forums/suggestions.517/) is.
Have a nice day!
