### ISSUE TITLE
Accessing Database/Replays Of Local PokemonShowdown build

### ISSUE THREAD

**Issue by curtdissel** [smogon/pokemon-showdown-client#1909]
Hullo All,

This might be more of a question than an issue. I will keep it short.

I am playing around with Pokemon Showdown Locally and was wondering where things such as the database and replays were saved.

The reason I ask is because I wanted to do analysis on matches and figured I could just grab data from the database and replay folder.

Upon looking through the code, I conclude that the replays for local builds of Pokemon showdown as well as the database are actually sent to a different server.

If my suspicion is right, my questions are thus.

1) Is there a way to use my own database for local Pokemon showdown builds?

2) Is there a way to save replays locally?

If I can't redirect replays/database usage, I hope to at least save a copy of the replay to my own machine. This will help me build my datasets.

**Comment by mia-pi-git** [comment]
You would need to run your own client and loginserver in order to redirect replays. As for databases, can you specify? What databases are you interested in? Users, ladders, etc?

**Comment by curtdissel** [comment]
Probably Users and Ladders.

I am big on collecting data and would like to create visualizations that go beyond most tools.

To build a Pokemon Coaching tool, I would need to know how the user is doing between different generations of the game and different tiers.

That way each user can get a unique coaching experience.

I may be able to do some of this without access to the database, but for my tools, I would either want to expand the database with new tables or just keep my tooling specific stuff in a separate one.

I do see that the Pokemonshowdown-loginserver does contain info about connecting to a database.

Questions
1) Are there steps for connecting showdown to a local loginserver/client?

My guess is that these values would be updated in the config. But I am not sure if this is trivial or not.
exports.routes = {
	root: 'pokemonshowdown.com',
	client: 'play.pokemonshowdown.com',
	dex: 'dex.pokemonshowdown.com',
	replays: 'replay.pokemonshowdown.com',
};

2) If the replays are JSON, would it be possible to just write that to a file before they are sent to the server? Although upon further thinking, the replays might  be constructed on the loginserver/client server.

**Comment by mia-pi-git** [comment]
> 2\. If the replays are JSON, would it be possible to just write that to a file before they are sent to the server? Although upon further thinking, the replays might  be constructed on the loginserver/client server.

All loginserver databases are stored in MySQL for the moment. 
> 1\. Are there steps for connecting showdown to a local loginserver/client?
For the client, yes you'd need to update the routes to your URLs. The loginserver we do not document since if it's run wrong, people's passwords can be stolen, so we need to be sure you know what you're doing.

**Comment by mia-pi-git** [comment]
Our [web APIs](https://github.com/smogon/pokemon-showdown-client/blob/master/WEB-API.md) may be of interest to you.

**Comment by curtdissel** [comment]
Questions
1) Are there ways to get full replays including: |request| and team info?

2) Would replays from my local Pokemon showdown matches be searchable with the same API?

**Comment by mia-pi-git** [comment]
> Are there ways to get full replays including: |request| and team info?
Inputlogs should store teams. If it's your own replay you can access said logs.
> Would replays from my local Pokemon showdown matches be searchable with the same API?
No, you need to upload from a registered side server or the main server.

**Comment by curtdissel** [comment]
Are there considerations to make full replay logs for random matches available? 

I think other formats might have privacy concerns, whereas random should be fair game to share full replays.

**Comment by Zarel** [comment]
Yes, inputlogs are publicly available in random battle replays.

**Comment by curtdissel** [comment]
Looking at this gen8 random battle:  1480445054

The replay doesn't contain the |request| tags or team info tags.

https://replay.pokemonshowdown.com/gen8randombattle-1480445054.log
https://replay.pokemonshowdown.com/gen8randombattle-1480445054.json

Is there a way to get complete information for random battles?

**Comment by mia-pi-git** [comment]
`|request|` is only sent to the user receiving the request. It's not saved anywhere. You'd have to be playing battles & manually tracking it.

**Comment by curtdissel** [comment]
Thanks for this important information. You two have been super helpful.

If the team info such as stats isn't saved inside of the replay file, then that is information that is stored in the DB for that match.

Which I think the easiest thing to do is actually manually track the information in real time as it is happening.

Otherwise to get the complete picture of a match that took place, I would need the replay file, plus the database record of the team configuration.

**Comment by curtdissel** [comment]
I will close this bug for now and see if I can use the information provided to get everything i need.

If that is the case, I should not need to go down the longer paths of running the client, login-server

**Comment by Zarel** [comment]
You can reconstruct everything by passing the inputlog as stdin to `./pokemon-showdown simulate-battle`.

For instance, save the inputlog as `inputlog.txt`, and then try something like `cat inputlog.txt | ./pokemon-showdown simulate-battle`.

You'll get something starting with

```
{"winner":"richard_tater","seed":[59793,62875,34188,55947],"turns":12,"p1":"Higuchi Kaede","p2":"richard_tater","p1team":[{"name":"Kyurem","species":"Kyurem","gender":"N","shiny":false,"gigantamax":false,"level":80,"moves":["earthpower","freezedry","roost","dracometeor"],"ability":"Pressure","evs":{"hp":85,"atk":0,"def":85,"spa":85,"spd":85,"spe":85},"ivs":{"hp":31,"atk":0,"def":31,"spa":31,"spd":31,"spe":31},"item":"Heavy-Duty Boots"},{"name":"Tentacruel","species":"Tentacruel","gender":"","shiny":false,"gigantamax":false,"level":84,"moves":["haze","rapidspin","scald","knockoff"],"ability":"Clear Body","evs":{"hp":85,"atk":85,"def":85,"spa":85,"spd":85,"spe":85},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"item":"Black Sludge"},{"name":"Arctovish","species":"Arctovish","gender":"N","shiny":false,"gigantamax":false,"level":86,"moves":["iciclecrash","fishiousrend","psychicfangs","bodyslam"],"ability":"Water Absorb","evs":{"hp":85,"atk":85,"def":85,"spa":85,"spd":85,"spe":85},"ivs":{"hp":31,"atk":31,"def":31,"spa":31,"spd":31,"spe":31},"item":"Choice Band"},{"name":"Swoobat","species":"Swoobat","gender":"","shiny":false,"gigantamax":false,"level":86,"moves":["calmminsideupdate
p1
|request|{"active":[{"moves":[{"move":"Earth Power","id":"earthpower","pp":16,"maxpp":16,"target":"normal","disabled":false},{"move":"Freeze-Dry","id":"freezedry","pp":32,"maxpp":32,"target":"normal","disabled":false},{"move":"Roost","id":"roost","pp":16,"maxpp":16,"target":"self","disabled":false},{"move":"Draco Meteor","id":"dracometeor","pp":8,"maxpp":8,"target":"normal","disabled":false}],"canDynamax":true,"maxMoves":{"maxMoves":[{"move":"maxquake","target":"adjacentFoe"},{"move":"maxhailstorm","target":"adjacentFoe"},{"move":"maxguard","target":"self"},{"move":"maxwyrmwind","target":"adjacentFoe"}]}}],"side":{"name":"Higuchi Kaede","id":"p1","pokemon":[{"ident":"p1: Kyurem","details":"Kyurem, L80","condition":"331/331","active":true,"stats":{"atk":213,"def":190,"spa":254,"spd":190,"spe":198},"moves":["earthpower","freezedry","roost","dracometeor"],"baseAbility":"pressure","item":"heavydutyboots","pokeball":"pokeball","ability":"pressure"},{"ident":"p1: Tentacruel","details":"Tentacruel, L84, M","condition":"272/272","active":false,"stats":{"atk":166,"def":157,"spa":183,"spd":250,"spe":216},"moves":["haze","rapidspin","scald","knockoff"],"baseAbility":"clearbody","item":"blacksludge","pokeball":"pokeball","ability":"clearbody"},{"ident":"p1: Arctovish","details":"Arctovish, L86","condition":"295/295","active":false,"stats":{"atk":204,"def":221,"spa":187,"spd":204,"spe":144},"moves":["iciclecrash","fishiousrend","psychicfangs","bodyslam"],"baseAbility":"waterabsorb","item":"choiceband","pokeball":"pokeball","ability":"waterabsorb"},{"ident":"p1: Swoobat","details":"Swoobat, L86, M","condition":"255/255","active":false,"stats":{"atk":103,"def":144,"spa":182,"spd":144,"spe":245},"moves":["calmmind","roost","storedpower","heatwave"],"baseAbility":"simple","item":"heavydutyboots","pokeball":"pokeball","ability":"simple"},{"ident":"p1: Solgaleo","details":"Solgaleo, L72","condition":"316/316","active":false,"stats":{"atk":239,"def":196,"spa":205,"spd":170,"spe":182},"moves":["closecombat","knockoff","psychicfangs","sunsteelstrike"],"baseAbility":"fullmetalbody","item":"choiceband","pokeball":"pokeball","ability":"fullmetalbody"},{"ident":"p1: Tyrantrum","details":"Tyrantrum, L82, F","condition":"269/269","active":false,"stats":{"atk":246,"def":242,"spa":160,"spd":144,"spe":164},"moves":["outrage","closecombat","headsmash","earthquake"],"baseAbility":"rockhead","item":"choiceband","pokeball":"pokeball","ability":"rockhead"}]}}
```

**Comment by curtdissel** [comment]
Thanks, I will look into modifying my server to record the input log. 

The ability to reconstruct the match from inputLog is interesting.

Originally I was just gonna save the match/team details.

But this inputLog thing, can allow me to process the same match multiple times with different methods.

**Comment by mia-pi-git** [comment]
All battles record input logs. Use /exportinputlog to export it (requires the consent of both players - you can also access it from the server code with `room.battle.inputLog`)
