### ISSUE TITLE
Error in BattleTextParser

### ISSUE THREAD

**Issue by lewell94** [smogon/pokemon-showdown-client#1984]
I think this revert is causing issues: https://github.com/smogon/pokemon-showdown-client/commit/f51402ef6c78818a4beae99da630ea3b1869176d

<img width="469" alt="image" src="https://user-images.githubusercontent.com/6898988/181291265-fbd024f8-7a98-4cc8-a491-95de2f6f4782.png">

**Comment by Marty-D** [comment]
No, it the thing that was reverted that caused the issue; reload your page.

**Comment by lewell94** [comment]
I've emptied the cache and done a hard reload but still occurring for me
