### ISSUE TITLE
[Teambuilder] Filtering moves by type/category overwrites existing moves

### ISSUE THREAD

**Issue by Rebmiami** [smogon/pokemon-showdown-client#1991]
Filtering moves by type or category in the team builder will seemingly delete the move from your Pokémon's moveset, however it still appears highlighted in the moves list. Attempting to delete the "phantom" move will cause strange effects when you go back to the team view, as shown in this recording:

https://user-images.githubusercontent.com/59275598/187088226-dcee32e4-3de1-4dc8-99d4-0a42027b7cb7.mp4

Occurs on nwjs app and Firefox on Windows 10. Have not tested on other platforms.

**Comment by joebangara43903** [comment]
![image](https://user-images.githubusercontent.com/131228993/232965391-e2ead865-858e-480a-a5fd-fd3faae24a65.png)
