### ISSUE TITLE
Importing a team with hidden power causes ivs decrease even if the pokemon can hypertrain

### ISSUE THREAD

**Issue by EvGym** [smogon/pokemon-showdown-client#2091]
If you import a team and one of the pokemon has a hidden power move, the pokemon's IVs will be modified to have that hidden power type. This only happens when importing a team and will correct itself if you edit hidden power or increase the IVs manually. This appears to occur in all formats where hyper training is available.

I am looking into it myself but I have little experience working on the client. Will let you know if I figure out how to fix it

**Comment by EvGym** [comment]
I have never launched a Client locally so anyone else taking this on would be preferred. I will try and figure out how to run my own custom client in the meantime.

**Comment by EvGym** [comment]
Looks like the issue is in panel-teamdropdown.tsx around line 397-408

there needs to be a generation check added to see if ivs need to be decreased. If that is even possible

**Comment by EvGym** [comment]
My recommended fix is to just not make the drop-down try and fix this. Worst case scenario the team fails validation and people can fix it either manually or by resetting the hp type.

People can always import illegal teams. We really don't need to police this as the validator will catch it. Most people import legal teams anyway so I don't believe this will effect many much of anyone if we remove it.

**Comment by EvGym** [comment]
https://github.com/smogon/pokemon-showdown-client/pull/2092

Got the fix in. Far easier than I thought it would be. Even though I had to drop the generation-specific response.

**Comment by joebangara43903** [comment]
![image](https://user-images.githubusercontent.com/131228993/232965318-6ac85e9a-2aea-49af-a1d0-c5f75974624d.png)

**Comment by joebangara43903** [comment]
![image](https://user-images.githubusercontent.com/131228993/232965333-ba4bab18-2da0-4c8e-8925-b4d7d9c65bb9.png)

**Comment by EvGym** [comment]
This still needs fixing as at no point should every future gen be plagued by their teams being modified due to an old mechanic that doesn't even apply to them anymore.
