### ISSUE TITLE
Illusion, search IDs, and UI assistance

### ISSUE THREAD

**Issue by Slayer95** [smogon/pokemon-showdown-client#314]
Illusion currently has a bug in the fact that it displays the level of the fake mon in the simulator, while in-game it displays the real level of the Pokémon with Illusion. This is -as an immediate cause- due to Pokémon getting identified client-side by their <code>searchid</code>, which is built from server-side <code>details</code>. As far as I can see, the overall server-side approach to Illusion in <code>BattlePokemon.getDetails</code> is sound (though I can see some room to improvement by taking advantage of the battle log <code>|split|</code> feature).

Currently, <code>searchid</code> includes.
- Species
- Nickname
- Gender
- Shinyness
- Level

Additionally to its not copying level, Illusion should -when it becomes possible- display the copied Poké Ball (related: #306). Similarly, <code>searchid</code> should include Poké Ball information, and it would be straightforward to remove the level data from <code>searchid</code>.

However, it stands that a different displayed level can be used in a metagame without Species Clause to discover that the opponent has 2 or more of a species (if there is no Team Preview), or associate items/moves/abilities to one or more of them. Similarly, it's theoretically possible to identify Pokémon based on whether they have a certain item or activate an ability on switch-in (or even afterwards, but its implementation is unrealistic imo). Automating the process of identifying different Pokémon on the basis of items/abilities would be potentially a very significant assistance in formats such as Hackmons.

Which concept would we like to implement?
Restrict <code>details</code> to the information conveyed by Illusion? If we don't do that, we would need to replace the level when Illusion is active. In that case, would we like to keep the amount of information in <code>details</code> the same (plus Poké Ball)? Or maybe expand it to obvious items and abilities? Something else?

**Comment by Zarel** [comment]
Illusion no longer displays the fake level. I don't know what the rest of this is about, but a number of other Illusion issues have been fixed since then, and we don't get complaints about Illusion UI anymore.
