### ISSUE TITLE
Allow seeing your own Pokemon even when trapped

### ISSUE THREAD

**Issue by xfix** [smogon/pokemon-showdown-client#962]
The Pokemon list would be grayed out to mark a switch that cannot be done, I suppose? It's useful to see list of your own Pokemon, even when game would prevent it (just like you can see list of Pokemon in actual game even after confirming a trap).

Might as well assign this to myself whoever can commit to this repository, I cannot do it myself however.

**Comment by Zarel** [comment]
This will require server changes to actually send the Pokémon list while trapped. I hope that can't be an information leak.

**Comment by scheibo** [comment]
I think I did this in #1554?
